title: PG Cert Computer Science e-Portfolio # your name (or website title) here
logo: "/images/grey.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi I'm Patz.
  <br><br>
  This is my e-Portfolio based on the work carried out in the PG Cert Computer Science programme of the University of Essex Online. 
  <br><br>
  Credits:
_Unit names, formative activities, e-portfolio activities, seminar activities, and Codio activities are all provided for by [The University of Essex Online](https://online.essex.ac.uk/) for the PG Cert Computer Science course.._

  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
